const WORDS = [
  { term: "Accounting department", def: "A department responsible for recording the company's financial transactions.", tr: "účtárna", unit: "Management" },
  { term: "Area manager", def: "A person responsible for the company's operations in a certain area.", tr: "oblastní manažer", unit: "Management" },
  { term: "Board of Directors", def: "Governing body of an incorporated firm. Its members (directors) are elected normally by the stockholders of the firm (generally at an annual general meeting or AGM) to govern the firm and look after the stockholders' interests.", tr: "správní rada, představenstvo", unit: "Management" },
  { term: "Bonus", def: "Money added to someone's wages, especially as a reward for good work.", tr: "prémie, odměna", unit: "Management" },
  { term: "Branch manager", def: "A person responsible for a local office of a large company (e.g. a bank).", tr: "manažer pobočky", unit: "Management" },
  { term: "CEO / Managing Director / Director General", def: "The person with the most authority in a large company (esp. AmE); someone who is in charge of a large company or organisation (BrE).", tr: "výkonný ředitel, generální ředitel", unit: "Management" },
  { term: "CFO / VP of Finance / Financial Director / Financial Manager", def: "The person responsible for the financial management of a company.", tr: "finanční ředitel", unit: "Management" },
  { term: "Chain of command", def: "A system in an organisation by which decisions are made and passed from people at the top of the organisation to people lower down.", tr: "řetězec velení, systém subordinace", unit: "Management" },
  { term: "Chairman", def: "Someone who is in charge of a meeting or directs the work of a committee or an organisation.", tr: "předseda, předsedající", unit: "Management" },
  { term: "CMO / VP of Marketing / Marketing Director / Marketing Manager", def: "The person responsible for marketing, i.e. finding out what the customers want (market research) and providing it to them (the right product, for the right price, at the right place, using the right promotion).", tr: "marketingový ředitel", unit: "Management" },
  { term: "Commission", def: "An extra amount of money that is paid to a person or organisation according to the value of the goods they have sold or the services they have provided (typical e.g. for real estate agents).", tr: "provize", unit: "Management" },
  { term: "COO / VP of Operations / Operations Director / Operations Manager", def: "The person responsible for how the company is run on a day-to-day basis.", tr: "provozní ředitel", unit: "Management" },
  { term: "Crew leader", def: "A person responsible for a group of people who work together (e.g. on a plane, ship, etc.).", tr: "vedoucí skupiny/týmu/štábu", unit: "Management" },
  { term: "Department manager", def: "A person responsible for one part of a company that deals with a particular area of work (e.g. marketing, human resources, etc.).", tr: "manažer oddělení", unit: "Management" },
  { term: "Division manager", def: "A person responsible for one division, i.e. one (usually large) separate part of a company.", tr: "manažer divize", unit: "Management" },
  { term: "(Executive) director", def: "Someone who controls or manages a company.", tr: "(výkonný) ředitel", unit: "Management" },
  { term: "Finance department", def: "A department responsible for managing a company's money.", tr: "finanční oddělení", unit: "Management" },
  { term: "Foreman", def: "Someone in charge of a group of workers, e.g. in a factory.", tr: "mistr, vedoucí dílny", unit: "Management" },
  { term: "Human Resources (HR) department / Personnel department", def: "A department responsible for recruitment of new staff, training and development of existing employees, performance appraisals, rewarding (managing the pay and benefits systems) and dismissal of employees.", tr: "personální oddělení, oddělení lidských zdrojů", unit: "Management" },
  { term: "Job description", def: "An official list of the work and responsibilities that you have in your job.", tr: "popis práce (soupis pracovních povinností)", unit: "Management" },
  { term: "Job rotation", def: "The practice of regularly changing the person who does a particular job; this means that one person switches between doing different tasks for the same employer.", tr: "rotace pracovníků", unit: "Management" },
  { term: "Job security", def: "Not being in danger of losing your job.", tr: "jistota zaměstnání (jistota pracovního místa)", unit: "Management" },
  { term: "Management", def: "1. The act of organising and coordinating the activities of a business in order to achieve defined objectives. 2. A group of people who run and control a business or organisation.", tr: "1. řízení; 2. management, vedení firmy", unit: "Management" },
  { term: "Marketing department", def: "A department responsible for finding out what customers want, using that information to design products and services and selling them effectively.", tr: "marketingové oddělení", unit: "Management" },
  { term: "Morale", def: "The level of confidence and positive feelings that people have, especially people who work together, who belong to the same team, etc.", tr: "morálka, nálada (týmu)", unit: "Management" },
  { term: "Non-executive director", def: "One of the directors of a company who gives advice, but who does not make decisions about how the company is run.", tr: "ředitel s poradní funkcí, bez výkonné pravomoci", unit: "Management" },
  { term: "Office manager", def: "A person who is responsible for the organisation of the work in an office.", tr: "vedoucí kanceláře", unit: "Management" },
  { term: "Pay", def: "The money that you earn by working.", tr: "plat", unit: "Management" },
  { term: "Performance appraisal / Performance review", def: "A meeting between an employee and a manager to discuss the quality of the employee's work, and areas for future progress.", tr: "hodnocení výkonu (práce zaměstnance)", unit: "Management" },
  { term: "Perks / Employee benefits / Fringe benefits", def: "Things that you get legally from your work in addition to your pay, such as goods, meals, or the use of a car.", tr: "zaměstnanecké výhody", unit: "Management" },
  { term: "Personal assistant", def: "Someone who works for one person (often a senior manager) and helps them do their job.", tr: "osobní asistent(ka)", unit: "Management" },
  { term: "Personnel / Staff / Employees", def: "The people who work for a company or an organisation.", tr: "personál, zaměstnanci", unit: "Management" },
  { term: "Plant manager", def: "The head of a factory or other place where goods are manufactured or resources such as energy are produced.", tr: "manažer závodu", unit: "Management" },
  { term: "President", def: "The person who has the highest position in a company or organisation (esp. AmE).", tr: "prezident, předseda", unit: "Management" },
  { term: "Production department / Operations", def: "A department responsible for turning inputs (e.g. raw materials, components) into outputs (e.g. finished products) smoothly and efficiently.", tr: "výrobní oddělení", unit: "Management" },
  { term: "Profit sharing", def: "A system in which employees receive a share of the net profits of the business.", tr: "podíl na zisku", unit: "Management" },
  { term: "Promotion", def: "A move to a more important job or position in a company or organisation.", tr: "povýšení", unit: "Management" },
  { term: "Regional manager", def: "A manager responsible for coordinating the company's operations in a certain region (the size of the region can vary from a single county to multiple countries).", tr: "regionální manažer", unit: "Management" },
  { term: "Remuneration", def: "An amount of money that is paid to somebody for the work they have done.", tr: "odměna, odměňování", unit: "Management" },
  { term: "Research & development (R&D) department", def: "A department responsible for discovering solutions to existing problems or creating new or improved products.", tr: "výzkum a vývoj", unit: "Management" },
  { term: "Salary", def: "Money that you receive as payment from the organisation you work for, usually paid to you every month (typical of white collar workers).", tr: "(stálý) plat", unit: "Management" },
  { term: "Sales department", def: "A department that sells a company's products.", tr: "oddělení prodeje, obchodní oddělení", unit: "Management" },
  { term: "Sanction", def: "A form of punishment that can be used if someone disobeys a rule or law or does not do their job well.", tr: "sankce, postih", unit: "Management" },
  { term: "Secretary", def: "Someone who works in an office typing letters, keeping records, answering telephone calls, arranging meetings.", tr: "sekretář(ka)", unit: "Management" },
  { term: "Section leader", def: "A person responsible for one part of an organisation.", tr: "vedoucí sekce/oddělení", unit: "Management" },
  { term: "Shift supervisor", def: "A person responsible for a group of workers who work at a particular time.", tr: "vedoucí směny", unit: "Management" },
  { term: "Social club", def: "A club where its members can go to spend time, talk, drink, etc. with other members.", tr: "společenský klub", unit: "Management" },
  { term: "Store manager", def: "A person responsible for a store, i.e. a place where people buy things or a place where things are kept.", tr: "vedoucí prodejny/skladu", unit: "Management" },
  { term: "Subordinate", def: "Someone who has a lower position and less authority than you.", tr: "podřízený", unit: "Management" },
  { term: "Superior", def: "Someone who has a higher rank or position than you.", tr: "nadřízený", unit: "Management" },
  { term: "Supervisor", def: "A person who is in charge of a group of people or an area of work and who makes sure that the work is done correctly and according to the rules.", tr: "vedoucí, dohled", unit: "Management" },
  { term: "Team building / Teambuilding", def: "The process of getting employees to work together well and communicate effectively.", tr: "budování/utváření týmu", unit: "Management" },
  { term: "Wage", def: "Money you earn that is paid according to the number of hours, days, or weeks that you work (typical for blue collar workers).", tr: "mzda", unit: "Management" },
  { term: "Workforce / Labour force", def: "All the people who work in a particular industry or company.", tr: "pracující, zaměstnanci (všichni zaměstnanci dané firmy/odvětví)", unit: "Management" },
  { term: "Assumption", def: "A belief or feeling that something is true or that something will happen, although there is no proof.", tr: "předpoklad, domněnka", unit: "Cross" },
  { term: "Collectivist", def: "Emphasising the collective rather than individual action or identity.", tr: "kolektivistický, podřizující se kolektivu", unit: "Cross" },
  { term: "Cross-cultural differences", def: "Differences that arise when people from different cultures work and live together.", tr: "rozdíly/odlišnosti mezi kulturami", unit: "Cross" },
  { term: "Cross-cultural skills", def: "Competences that refer to the knowledge and motivation that enable individuals to adapt effectively in cross-cultural environments.", tr: "dovednosti, které nám pomohou správně se chovat a řešit situace, které mohou vzniknout střetem mezi různými kulturami", unit: "Cross" },
  { term: "Cross-cultural training", def: "Training that will teach employees to adapt effectively in cross-cultural environments.", tr: "trénink dovedností, které nám pomohou správně se chovat a řešit situace, které mohou vzniknout střetem mezi rozlišnými kulturami", unit: "Cross" },
  { term: "Cultural awareness", def: "Understanding of the differences between oneself and people from other countries or other backgrounds.", tr: "kulturní povědomí", unit: "Cross" },
  { term: "Cultural dimensions", def: "A set of preferences that distinguish one country from another.", tr: "kulturní dimenze (úrovně)", unit: "Cross" },
  { term: "Diverse workplace", def: "A workplace that is composed of employees with varying characteristics including religious and political beliefs, gender, ethnicity, education, socioeconomic background, sexual orientation and geographic location.", tr: "rozmanité pracoviště (kde spolupracují lidé pocházející z odlišných kulturních zázemí)", unit: "Cross" },
  { term: "Etiquette", def: "The formal rules of correct or polite behaviour in society or among members of a particular profession.", tr: "etiketa, pravidla chování", unit: "Cross" },
  { term: "Feminine", def: "Having the qualities or appearance considered to be typical of women; connected with women.", tr: "mající ženské rysy chování a osobnosti", unit: "Cross" },
  { term: "Individualistic", def: "Following the belief that individual people in society should have the right to make their own decisions, etc., rather than be controlled by the government or any other institution.", tr: "individualistický, samostatný, jednotlivý, osobitý", unit: "Cross" },
  { term: "Masculine", def: "Having the qualities or appearance considered to be typical of men; connected with or like men.", tr: "mající mužské rysy chování a osobnosti", unit: "Cross" },
  { term: "Negotiate", def: "To try to reach an agreement by formal discussion.", tr: "vyjednávat", unit: "Cross" },
  { term: "Non-verbal communication", def: "Communication which includes gestures, facial expressions, and body positions (known collectively as 'body language'), as well as unspoken understandings.", tr: "nonverbální komunikace", unit: "Cross" },
  { term: "Stereotype", def: "A fixed idea or image that many people have of a particular type of person or thing, but which is often not true in reality.", tr: "stereotyp; jednotvárný, ustálený, navyklý vzorec chování a myšlení", unit: "Cross" },
  { term: "Cyclical unemployment", def: "Unemployment resulting from fluctuations in economic activity.", tr: "cyklická nezaměstnanost", unit: "Recruitment" },
  { term: "Covering letter / Cover letter", def: "A letter containing extra information that you send with a CV/resume.", tr: "průvodní/motivační dopis", unit: "Recruitment" },
  { term: "Frictional unemployment", def: "Unemployment caused by new entrants to the job market and people who have left their jobs to look for and find other jobs.", tr: "dočasná nezaměstnanost", unit: "Recruitment" },
  { term: "Headhunter", def: "A third-party recruiter who works on behalf of an employer and seeks out candidates for executive and professional positions on their behalf.", tr: "lovec mozků", unit: "Recruitment" },
  { term: "Labour force / Workforce", def: "All people of working age, both employed and unemployed.", tr: "pracovní síla", unit: "Recruitment" },
  { term: "Outsource", def: "To contract out a business process to another party.", tr: "zadávat subdodavatelské zakázky", unit: "Recruitment" },
  { term: "Payroll", def: "A list of all financial records of salaries for an employee, wages, bonuses and deductions.", tr: "výplatní listina", unit: "Recruitment" },
  { term: "Promotion (recruitment context)", def: "A move to a more senior position in a company or organisation, decided upon by the employee's superiors.", tr: "povýšení", unit: "Recruitment" },
  { term: "Recruitment", def: "The overall process of attracting, selecting and appointing suitable candidates for jobs within an organisation.", tr: "nábor, přijímání pracovních sil", unit: "Recruitment" },
  { term: "Recruitment agency / Employment agency", def: "A business that finds employers or employees for those seeking them.", tr: "personální agentura", unit: "Recruitment" },
  { term: "Redundancy pay", def: "Money paid to workers when they are made redundant.", tr: "odstupné", unit: "Recruitment" },
  { term: "Shortlist", def: "A list of candidates for a job, prize, award, political position, etc., that has been reduced from a longer list of candidates.", tr: "užší seznam", unit: "Recruitment" },
  { term: "Structural unemployment", def: "Unemployment resulting from changes in the economy itself.", tr: "strukturální nezaměstnanost", unit: "Recruitment" },
  { term: "Unemployment rate", def: "The percentage of people in the labour force who cannot find employment but are looking for it.", tr: "míra nezaměstnanosti", unit: "Recruitment" },
  { term: "Vacancy", def: "A job position that is available to be filled.", tr: "volné místo", unit: "Recruitment" },
  { term: "Above the line advertising", def: "Advertising in the mass media.", tr: "nadlinková/mediální reklama", unit: "Marketing" },
  { term: "Advertising", def: "A form of marketing communication used to call public attention to a product, especially by paid announcements in newspapers and magazines, over radio or television, on billboards, etc.", tr: "reklama", unit: "Marketing" },
  { term: "Advertising budget", def: "Money planned for spending on advertising.", tr: "rozpočet na reklamu", unit: "Marketing" },
  { term: "Advertising campaign", def: "An organised course of action to promote a product.", tr: "reklamní kampaň", unit: "Marketing" },
  { term: "Below the line advertising", def: "Advertising by means such as direct mail, email, promotional events, etc.", tr: "podlinková reklama", unit: "Marketing" },
  { term: "Brand", def: "A distinguishing symbol, mark, logo, name, word, sentence or a combination of these items that companies use to distinguish their product from others in the market.", tr: "obchodní značka", unit: "Marketing" },
  { term: "Brand extension", def: "A common method of launching a new product by using an existing brand name on a new product in a different category.", tr: "rozšiřování značky", unit: "Marketing" },
  { term: "Brand image", def: "The impression in the consumers' mind of a brand's total personality.", tr: "image značky", unit: "Marketing" },
  { term: "Brand loyalty", def: "Where a person buys products from the same manufacturer repeatedly rather than from other suppliers.", tr: "věrnost značce", unit: "Marketing" },
  { term: "Brand recognition", def: "The extent to which the general public (or an organisation's target market) is able to identify a brand by its attributes.", tr: "znalost značky, povědomí o značce", unit: "Marketing" },
  { term: "Brand stretching", def: "The act of using an established brand name in order to introduce unrelated products.", tr: "přenášení značky (na nové kategorie produktů)", unit: "Marketing" },
  { term: "Branding", def: "The process involved in creating a unique name and image for a product in the consumers' mind, mainly through advertising campaigns with a consistent theme.", tr: "branding, budování značky", unit: "Marketing" },
  { term: "Commercial", def: "A television or radio advertisement.", tr: "reklama (v televizi či rádiu)", unit: "Marketing" },
  { term: "Commercial break", def: "An interruption of a programme, or an intermission between programmes, during which advertisements are broadcast.", tr: "reklamní přestávka", unit: "Marketing" },
  { term: "Counterfeit brands", def: "Products made to look exactly like famous brands, in order to deceive people.", tr: "padělané značky", unit: "Marketing" },
  { term: "Demand", def: "Desire for a certain good or service supported by the capacity to purchase it.", tr: "poptávka", unit: "Marketing" },
  { term: "Desk research / Secondary research", def: "Searching for information in existing sources.", tr: "sekundární výzkum", unit: "Marketing" },
  { term: "Field research / Primary research", def: "Collecting primary (original, otherwise unavailable) data.", tr: "primární výzkum", unit: "Marketing" },
  { term: "Focus group", def: "A representative group of people questioned together about their opinions on something.", tr: "skupinová diskuse", unit: "Marketing" },
  { term: "Intangible", def: "Not existing as a physical thing but still valuable to a company.", tr: "nehmotný", unit: "Marketing" },
  { term: "Logo", def: "A printed design or symbol that a company or an organisation uses as its special sign.", tr: "logo", unit: "Marketing" },
  { term: "Market research", def: "The gathering and studying of data related to consumer preferences, purchasing power, etc., especially prior to introducing a product on the market.", tr: "výzkum trhu", unit: "Marketing" },
  { term: "Online survey", def: "An investigation of the opinions of people conducted on the internet.", tr: "internetový průzkum", unit: "Marketing" },
  { term: "Own brand / Private brand / Private label", def: "A brand owned not by a manufacturer or producer but by a retailer or supplier who gets its goods made by a contract manufacturer under its own label.", tr: "privátní značka, maloobchodní značka", unit: "Marketing" },
  { term: "Pop-up ad", def: "A form of online advertisement that shows up in a new browser window.", tr: "automaticky otvíraná reklamní okna", unit: "Marketing" },
  { term: "Premium brand", def: "A brand that is respected as holding greater brand value than other brands; they target high-income customers and are designed to convey an impression of exclusiveness.", tr: "prémiová značka", unit: "Marketing" },
  { term: "Product differentiation", def: "A marketing process of distinguishing a product or service from others to make it more attractive to a particular target market; it involves differentiating it from competitors' products as well as a firm's own products.", tr: "produktová diferenciace, odlišování výrobků", unit: "Marketing" },
  { term: "Product placement", def: "The appearance of or reference to a product in film, television, or other media.", tr: "umisťování komerčních výrobků", unit: "Marketing" },
  { term: "Public Relations (PR)", def: "The practice of managing the spread of information between an individual or an organisation and the public.", tr: "public relations, vztahy s veřejností", unit: "Marketing" },
  { term: "Questionnaire", def: "A list of questions submitted for replies that can be analysed for usable information.", tr: "dotazník", unit: "Marketing" },
  { term: "Response rate", def: "The number of people who answered a survey divided by the number of people in the sample.", tr: "návratnost (dotazníku), míra odpovědí", unit: "Marketing" },
  { term: "Sales promotion", def: "The techniques for stimulating sales achieved through contests, demonstrations, discounts, point-of-sale displays, special offers and similar activities.", tr: "podpora prodeje", unit: "Marketing" },
  { term: "Sample", def: "A group of people who are used for getting information about a larger group or about the whole population.", tr: "vzorek", unit: "Marketing" },
  { term: "Tagline / Slogan", def: "A word or phrase that is easy to remember, used for example by a political party or in advertising to attract people's attention or to suggest an idea quickly.", tr: "reklamní slogan", unit: "Marketing" },
  { term: "Tangible", def: "That you can touch and feel (asset, attribute).", tr: "hmotný", unit: "Marketing" },
  { term: "Trademark (TM)", def: "A name, symbol or design that a company uses for its products and that cannot be used by anyone else.", tr: "ochranná známka", unit: "Marketing" },
  { term: "Viral marketing", def: "Marketing techniques that use social networking services and other technologies to try to achieve marketing objectives.", tr: "virální marketing", unit: "Marketing" },
  { term: "Word-of-mouth (WOM)", def: "The passing of information from person to person by oral communication.", tr: "word of mouth, 'slovo z úst', ústní doporučení", unit: "Marketing" },
  { term: "Asset", def: "A thing of value, especially property, that a person or company owns, which can be used or sold to pay debts.", tr: "majetek", unit: "Banking" },
  { term: "Bond", def: "An official paper given by the government or a company to show that you have lent them money that they will pay back to you at a particular interest rate.", tr: "dluhopis", unit: "Banking" },
  { term: "Building society", def: "An organisation like a bank that lends money to people who want to buy a house. People also save money with a building society.", tr: "stavební spořitelna", unit: "Banking" },
  { term: "Central bank", def: "A national bank that does business with the government and other banks, and issues the country's coins and paper money.", tr: "centrální banka", unit: "Banking" },
  { term: "Commercial bank / Retail bank", def: "A bank that offers services to the general public and to businesses.", tr: "komerční banka", unit: "Banking" },
  { term: "Conglomerate", def: "A large company formed by joining together different firms.", tr: "konglomerát", unit: "Banking" },
  { term: "Coupon", def: "The amount of interest that a bond pays.", tr: "výnos/úrok z dluhopisu, kupón", unit: "Banking" },
  { term: "Credit", def: "1. Money that you borrow from a bank; a loan. 2. An arrangement that you make, with a shop/store for example, to pay later for something you buy. 3. To add an amount of money to somebody's bank account.", tr: "1. úvěr, půjčka; 2. úvěr; 3. připsat", unit: "Banking" },
  { term: "Credit card", def: "A plastic card that you can use to buy goods and services and pay for them later.", tr: "kreditní karta", unit: "Banking" },
  { term: "Current account (BrE) / Checking account (AmE)", def: "A type of bank account that you can take money out of at any time, and that provides you with a debit card.", tr: "běžný účet", unit: "Banking" },
  { term: "Debit card", def: "A plastic card that can be used to take money directly from your bank account when you pay for something.", tr: "debetní karta", unit: "Banking" },
  { term: "Debt", def: "A sum of money that somebody owes.", tr: "dluh", unit: "Banking" },
  { term: "Default", def: "To fail to do something that you legally have to do, especially by not paying a debt.", tr: "nezaplatit; neplnění závazku", unit: "Banking" },
  { term: "Deflation", def: "A reduction in the amount of money in a country's economy so that prices fall or remain the same.", tr: "deflace", unit: "Banking" },
  { term: "Deposit", def: "1. A sum of money that is paid into a bank account. 2. A sum of money that is given as the first part of a larger payment. 3. A sum of money paid as a security when renting. 4. To put money into a bank account.", tr: "1. vklad; 2. záloha; 3. kauce, vratná záloha, jistina; 4. uložit peníze, deponovat", unit: "Banking" },
  { term: "Direct debit", def: "An instruction to your bank to allow somebody else to take an amount of money from your account on a particular date, especially to pay bills.", tr: "inkaso", unit: "Banking" },
  { term: "Dividend", def: "An amount of the profits that a company pays to people who own shares in the company.", tr: "dividenda", unit: "Banking" },
  { term: "Embezzle", def: "To steal money that you are responsible for or that belongs to your employer.", tr: "zpronevěřit, defraudovat", unit: "Banking" },
  { term: "Hedge fund", def: "An investment fund involving a group of people who take high risks with their investments in order to try and make a lot of money.", tr: "hedgeový fond", unit: "Banking" },
  { term: "High-yield (grade) bond", def: "A type of bond that pays a high rate of interest because there is a lot of risk involved, also called junk bond.", tr: "rizikový dluhopis/podřadná obligace", unit: "Banking" },
  { term: "Insurance company", def: "A company whose business is providing and selling insurance.", tr: "pojišťovna", unit: "Banking" },
  { term: "Interest rate", def: "Percentage paid by either the borrower on a loan or by the bank on money deposited.", tr: "úroková míra/sazba", unit: "Banking" },
  { term: "Intermediary", def: "A person or an organisation that helps other people or organisations to make an agreement by being a means of communication between them.", tr: "zprostředkovatel", unit: "Banking" },
  { term: "Internet bank", def: "A bank that operates over the internet.", tr: "internetová banka", unit: "Banking" },
  { term: "Investment bank", def: "A bank that deals with large businesses.", tr: "investiční banka", unit: "Banking" },
  { term: "Investment-grade bond", def: "A secure bond that generally pays low rate of interest.", tr: "dobře investičně hodnocený dluhopis", unit: "Banking" },
  { term: "Launder (money)", def: "To move money that has been obtained illegally into foreign bank accounts or legal businesses so that it is difficult for people to know where the money came from.", tr: "prát (špinavé peníze)", unit: "Banking" },
  { term: "Liability", def: "Money that is owed to someone and has to be paid in the future, such as tax, debt, interest, and mortgage payments.", tr: "závazek", unit: "Banking" },
  { term: "Liquid", def: "In the form of money, rather than investments or property, or able to be changed into money easily.", tr: "likvidní", unit: "Banking" },
  { term: "Maturity", def: "The length of time for which a bond is issued.", tr: "splatnost", unit: "Banking" },
  { term: "Merger", def: "The act of joining two or more organisations or businesses into one.", tr: "fúze", unit: "Banking" },
  { term: "Microfinance bank", def: "A bank that provides loans to very poor people, usually in developing countries.", tr: "mikrofinanční instituce", unit: "Banking" },
  { term: "Money supply", def: "The total amount of money that exists in the economy of a country at a particular time.", tr: "zásoba (nabídka) peněz v ekonomice", unit: "Banking" },
  { term: "Mortgage", def: "A legal agreement by which a bank or similar organisation lends you money to buy a house, etc., and you pay the money back over a particular number of years; the sum of money that you borrow.", tr: "hypotéka", unit: "Banking" },
  { term: "Mutual fund", def: "Service where financial experts invest the money of many people in many different companies.", tr: "podílový fond/vzájemný fond", unit: "Banking" },
  { term: "Non-bank financial intermediary", def: "A financial services firm (not a bank) that usually offers a variety of financial services including leasing or pension funds.", tr: "nebankovní zprostředkovatel úvěru", unit: "Banking" },
  { term: "Overdraft", def: "The amount of money that you owe to a bank when you have spent more money than is in your bank account; an arrangement that allows you to do this.", tr: "přečerpání účtu, kontokorent", unit: "Banking" },
  { term: "Principal", def: "The amount of capital making up a bond or other loan.", tr: "jistina", unit: "Banking" },
  { term: "Private bank", def: "A bank that is owned by one person or by a small number of shareholders and which provides financial advice and services for very rich people.", tr: "soukromá banka", unit: "Banking" },
  { term: "Public company", def: "A company that sells shares in itself to the public.", tr: "akciová společnost", unit: "Banking" },
  { term: "Security", def: "A financial or investment instrument bought and sold in financial markets, such as a bond or a share (stock).", tr: "cenný papír", unit: "Banking" },
  { term: "Standing order", def: "An instruction that you give to your bank to pay somebody a fixed amount of money from your account on the same day each week/month, etc.", tr: "trvalý platební příkaz", unit: "Banking" },
  { term: "Stock", def: "1. The value of the shares in a company that have been sold (uncountable). 2. A share that somebody has bought in a company or business (countable, usually plural). 3. (British English) Money that is lent to a government at a fixed rate of interest.", tr: "1., 2. akcie; 3. dluhopis", unit: "Banking" },
  { term: "Share", def: "Any of the units of equal value into which a company is divided and sold to raise money; people who own shares receive part of the company's profits.", tr: "akcie (podíl)", unit: "Banking" },
  { term: "Stock exchange", def: "A place where shares are bought and sold.", tr: "burza cenných papírů", unit: "Banking" },
  { term: "Stock market", def: "The business of buying and selling shares in companies.", tr: "trh cenných papírů", unit: "Banking" },
  { term: "Takeover", def: "An act of taking control of a company by buying most of its shares.", tr: "převzetí", unit: "Banking" },
  { term: "Return", def: "The amount of profit that you get from your investment.", tr: "výnos", unit: "Banking" },
  { term: "Withdraw", def: "To take money out of a bank account.", tr: "vybrat, vyzvednout peníze", unit: "Banking" },
  { term: "Yield", def: "The rate of income an investor receives from their stocks and shares or bonds (commonly called securities).", tr: "výtěžek", unit: "Banking" },
  { term: "Capital gains tax", def: "A tax on the proceeds resulting from the sale of assets, e.g. houses, land, etc.", tr: "daň z kapitálových výnosů", unit: "Government" },
  { term: "Corporate tax", def: "A tax on the profits of companies.", tr: "daň z příjmu firem", unit: "Government" },
  { term: "Customs duty", def: "A tax on imports, e.g. goods entering the country.", tr: "clo", unit: "Government" },
  { term: "Depression", def: "A long and severe recession in an economy.", tr: "deprese", unit: "Government" },
  { term: "Excise duty", def: "A tax placed on specific goods manufactured or sold within a country.", tr: "spotřební daň", unit: "Government" },
  { term: "Externality", def: "A consequence of an industrial or commercial activity which affects other parties.", tr: "externalita", unit: "Government" },
  { term: "Fiscal policy", def: "Government actions concerning taxation and public expenditure.", tr: "fiskální politika", unit: "Government" },
  { term: "Income tax", def: "A tax on earned income.", tr: "daň z příjmu", unit: "Government" },
  { term: "Infant industry", def: "An industry which is not fully developed, unable to survive competition.", tr: "mladé/vznikající průmyslové odvětví", unit: "Government" },
  { term: "Minimum wage", def: "The lowest remuneration that employers may legally pay to workers.", tr: "minimální mzda", unit: "Government" },
  { term: "Monetary policy", def: "Government or central bank actions concerning the rate of growth of money in circulation.", tr: "měnová politika", unit: "Government" },
  { term: "Pollution", def: "The presence in or introduction into the environment of a substance which has harmful or poisonous effects.", tr: "znečištění", unit: "Government" },
  { term: "Public good", def: "A good that is available for the society as a whole and not just individual members.", tr: "veřejný statek", unit: "Government" },
  { term: "Renewable", def: "A natural resource or source of energy not depleted when used.", tr: "obnovitelný", unit: "Government" },
  { term: "Tax avoidance", def: "The arrangement minimising tax liability within the law.", tr: "daňová optimalizace", unit: "Government" },
  { term: "Tax evasion", def: "The illegal non-payment or underpayment of tax.", tr: "daňový únik", unit: "Government" },
  { term: "Tax haven", def: "A country or independent area where taxes are levied at a lower rate.", tr: "daňový ráj", unit: "Government" },
  { term: "Tax rate", def: "The percentage paid in tax.", tr: "daňová sazba", unit: "Government" },
  { term: "Tax refund", def: "A sum of money that is paid back to the taxpayer.", tr: "daňový přeplatek", unit: "Government" },
  { term: "Tax relief", def: "A sum to be deducted from gross income in the calculation of taxable income.", tr: "daňová úleva", unit: "Government" },
  { term: "Tax return", def: "A form on which a taxpayer makes an annual statement of income.", tr: "daňové přiznání", unit: "Government" },
  { term: "Tax revenue", def: "An amount of money collected by the government.", tr: "daňové příjmy", unit: "Government" },
  { term: "Taxpayer", def: "A person who pays taxes.", tr: "daňový poplatník", unit: "Government" },
  { term: "Transfer payment", def: "Payments made by the government to individuals without requiring any goods or services in return.", tr: "transferová platba", unit: "Government" },
  { term: "Unemployment benefit", def: "Money paid by the government to people who are unemployed.", tr: "podpora v nezaměstnanosti", unit: "Government" },
  { term: "Value added tax", def: "A tax levied on goods at each stage of production.", tr: "daň z přidané hodnoty", unit: "Government" },
  { term: "Absolute advantage", def: "The ability of a country, individual, company, etc. to produce a good at a lower cost per unit than the cost at which any other entity produces that same good or service.", tr: "absolutní výhoda", unit: "Trade" },
  { term: "Balance of payments deficit", def: "The difference in the amount of money going out of a country and that which is coming in, when the total incoming is less than the total outgoing.", tr: "schodek platební bilance", unit: "Trade" },
  { term: "Balance of payments surplus", def: "The difference in the amount of money going out of a country and that which is coming in, when the total incoming is more than the total outgoing.", tr: "přebytek platební bilance", unit: "Trade" },
  { term: "Cargo", def: "The goods that are being carried in a ship, plane or another large vehicle.", tr: "náklad", unit: "Trade" },
  { term: "Comparative advantage", def: "The ability to produce something more efficiently (at a lower opportunity cost) than somebody else.", tr: "komparativní výhoda", unit: "Trade" },
  { term: "Dumping", def: "The act of charging a lower price for the goods in a foreign market than one charges for the same product in a domestic market.", tr: "dumping", unit: "Trade" },
  { term: "Economic sanctions", def: "Penalties imposed by one country on another country for political and social issues.", tr: "hospodářské sankce", unit: "Trade" },
  { term: "Economic stability", def: "Economic system of a nation that displays only minor fluctuations in the economy.", tr: "hospodářská stabilita", unit: "Trade" },
  { term: "Economies of scale", def: "The reduction in production costs that is a result of making and selling goods in large quantities.", tr: "úspory z rozsahu", unit: "Trade" },
  { term: "Embargo", def: "An official order to stop trade with another country.", tr: "embargo", unit: "Trade" },
  { term: "Export", def: "The business of sending goods to another country in order to sell them there, or a product that is sold to another country.", tr: "vývoz", unit: "Trade" },
  { term: "Free trade", def: "A policy by which governments of various nations do not restrict imports to or exports from their countries.", tr: "volný obchod", unit: "Trade" },
  { term: "Globalisation", def: "The process of international integration arising from the interchange of products, ideas and other aspects of culture.", tr: "globalizace", unit: "Trade" },
  { term: "Import", def: "The business of bringing goods from one country into another so they can be sold there; a product that is brought from one country into another so that it can be sold there.", tr: "dovoz", unit: "Trade" },
  { term: "International trade", def: "The exchange of goods and services between countries.", tr: "mezinárodní obchod", unit: "Trade" },
  { term: "Invisible trade", def: "Export and import of physically intangible items such as services.", tr: "vývoz a dovoz služeb", unit: "Trade" },
  { term: "Labour laws", def: "Laws regarding the relationship between employers and employees and between employers and trade unions.", tr: "pracovní právo", unit: "Trade" },
  { term: "Multinational corporation (MNC) / Transnational corporation (TNC)", def: "An organisation that owns or controls production of goods and services in one or more countries other than their home country.", tr: "nadnárodní korporace", unit: "Trade" },
  { term: "Opportunity cost", def: "A benefit, profit, or value of something that must be given up to acquire or achieve something.", tr: "náklady obětované příležitosti", unit: "Trade" },
  { term: "Perishable goods", def: "Goods that are likely to decay quickly.", tr: "zboží podléhající zkáze, rychle se kazící zboží", unit: "Trade" },
  { term: "Poverty gap", def: "The difference between the total population and those living in poverty (or the difference between rich and poor).", tr: "míra chudoby", unit: "Trade" },
  { term: "Protectionism", def: "Government actions and policies that restrict international trade.", tr: "protekcionismus, ochranářství", unit: "Trade" },
  { term: "Quota", def: "The number of goods and services that can be imported or exported during a particular time period, according to a government-imposed trade restriction that limits this.", tr: "kvóta", unit: "Trade" },
  { term: "Quote", def: "A statement of how much a job or service will cost; a price estimation.", tr: "cenová nabídka, kalkulace ceny", unit: "Trade" },
  { term: "Red tape", def: "An idiom referring to official rules that seem unnecessary and prevent things from being done quickly and easily.", tr: "byrokracie, 'úřední šiml'", unit: "Trade" },
  { term: "Self-sufficient", def: "Not requiring any help, support or interaction for survival; a self-sufficient economy does not trade with the outside world.", tr: "soběstačný", unit: "Trade" },
  { term: "Specialisation", def: "A method of production where a business or area focuses on the production of a limited scope of products or services in order to gain greater degrees of productive efficiency.", tr: "specializace", unit: "Trade" },
  { term: "Standard of living", def: "The amount of money and comfort people have in a particular society.", tr: "životní úroveň", unit: "Trade" },
  { term: "Subsidy", def: "Money that is paid by a government or organisation to make prices lower, reduce the cost of producing goods, etc.", tr: "dotace", unit: "Trade" },
  { term: "Tariff", def: "A tax imposed on imported goods and services, used to restrict trade.", tr: "tariff, clo, celní poplatek", unit: "Trade" },
  { term: "Trade alliance / Trade bloc / Trade agreement", def: "Treaty between two or more countries where trade barriers are reduced or eliminated among the participating countries.", tr: "mezinárodní obchodní dohoda, aliance", unit: "Trade" },
  { term: "Visible trade", def: "Export and import of goods at various stages of production.", tr: "vývoz a dovoz zboží", unit: "Trade" },
  { term: "Marketing concept", def: "Business approach identifying customer wants/needs, providing goods/services profitably", tr: "marketingový koncept", unit: "Primát" },
  { term: "Marketing strategy", def: "A plan to identify customer needs and bring together resources to satisfy them", tr: "marketingová strategie", unit: "Primát" },
  { term: "Marketing mix (4P)", def: "Product, Price, Place, Promotion – elements a firm uses to pursue marketing goals", tr: "marketingový mix", unit: "Primát" },
  { term: "Market segment", def: "A group of people for whom the product satisfies a similar need", tr: "tržní segment", unit: "Primát" },
  { term: "Niche market", def: "A small market segment with special characteristics", tr: "specializovaný trh", unit: "Primát" },
  { term: "Target market", def: "A group of people at whom a specific product is aimed", tr: "cílový trh", unit: "Primát" },
  { term: "Product portfolio", def: "The range of products marketed by a firm", tr: "produktové portfolio", unit: "Primát" },
  { term: "Product positioning", def: "The place/image your product has in customers' minds vs competitors", tr: "pozice produktu na trhu", unit: "Primát" },
  { term: "Above the line", def: "Mass advertising aimed at a wide audience (TV, billboards)", tr: "nadlinková reklama", unit: "Primát" },
  { term: "Below the line", def: "More targeted advertising (email, discount coupons)", tr: "podlinková reklama", unit: "Primát" },
  { term: "CSR", def: "Corporate Social Responsibility – ethical operations + positive societal impact", tr: "společenská odpovědnost firem", unit: "Primát" },
  { term: "Wholesaler", def: "A company that buys goods in bulk and sells to retailers", tr: "velkoobchodník", unit: "Primát" },
  { term: "Retailer", def: "A company that sells goods directly to final customers", tr: "maloobchodník", unit: "Primát" },
  { term: "Current account", def: "A bank account for everyday transactions, comes with a debit card", tr: "běžný účet", unit: "Primát" },
  { term: "Savings account", def: "A bank account for saving money and earning interest", tr: "spořicí účet", unit: "Primát" },
  { term: "Loan", def: "Money borrowed from a bank that must be repaid with interest", tr: "půjčka", unit: "Primát" },
  { term: "Equity", def: "The value of a company's shares / net worth", tr: "vlastní kapitál", unit: "Primát" },
  { term: "IPO (flotation)", def: "Initial Public Offering – first time a company sells shares to public", tr: "prvotní veřejná nabídka", unit: "Primát" },
  { term: "Launder money", def: "To move illegally obtained money through legal businesses", tr: "prát peníze", unit: "Primát" },
  { term: "Cash flow", def: "The movement of money in and out of a business", tr: "peněžní tok", unit: "Primát" },
  { term: "Fee", def: "Payment for a professional service", tr: "poplatek", unit: "Primát" },
  { term: "Turnover", def: "Total sales revenue / rate of employee replacement", tr: "obrat", unit: "Primát" },
  { term: "allocate → allocation", def: "to assign resources for a specific purpose", tr: "přidělit → přidělení", unit: "Primát" },
  { term: "borrow → borrowing/loan", def: "to take money with intent to repay", tr: "půjčit si → půjčka", unit: "Primát" },
  { term: "contribute → contribution", def: "to give to a common fund", tr: "přispět → příspěvek", unit: "Primát" },
  { term: "deposit → deposit", def: "to put money into an account", tr: "vložit → vklad", unit: "Primát" },
  { term: "earn → earnings", def: "to receive money for work", tr: "vydělat → výdělek", unit: "Primát" },
  { term: "embezzle → embezzlement", def: "to steal entrusted money", tr: "zpronevěřit → zpronevěření", unit: "Primát" },
  { term: "lend → loan/lending", def: "to give money to be repaid", tr: "půjčit → půjčka", unit: "Primát" },
  { term: "repay → repayment", def: "to pay back money owed", tr: "splatit → splátka", unit: "Primát" },
  { term: "spend → spending/expenditure", def: "to use money", tr: "utratit → výdaj", unit: "Primát" },
  { term: "withdraw → withdrawal", def: "to take money out of an account", tr: "vybrat → výběr", unit: "Primát" },
  { term: "refund → refund", def: "to give money back", tr: "vrátit peníze → vrácení", unit: "Primát" },
  { term: "go under / go bankrupt / go bust", def: "to fail financially", tr: "zkrachovat", unit: "Primát" },
  { term: "run up a debt", def: "to accumulate a debt", tr: "nadělat si dluh", unit: "Primát" },
  { term: "pay off a debt", def: "to repay a debt completely", tr: "splatit dluh", unit: "Primát" },
  { term: "be in debt", def: "to owe money", tr: "být v dluzích", unit: "Primát" },
  { term: "make a loss / run at a loss", def: "to lose money in business", tr: "mít ztrátu / být ztrátový", unit: "Primát" },
  { term: "obtain / take out a loan", def: "to get a loan", tr: "získat / vzít si půjčku", unit: "Primát" },
  { term: "default on a loan", def: "to fail to repay a loan", tr: "nesplácet půjčku", unit: "Primát" },
  { term: "VAT", def: "Value Added Tax – tax on goods at each stage of production", tr: "DPH", unit: "Primát" },
  { term: "Recession", def: "A period of economic decline", tr: "recese", unit: "Primát" },
  { term: "Welfare", def: "Government help for people (social care, benefits)", tr: "sociální péče", unit: "Primát" },
  { term: "Balance of payments", def: "Difference between money coming in and going out of a country", tr: "platební bilance", unit: "Primát" },
  { term: "Trade surplus", def: "When exports exceed imports", tr: "obchodní přebytek", unit: "Primát" },
  { term: "Trade deficit", def: "When imports exceed exports", tr: "obchodní deficit", unit: "Primát" },
  { term: "Multinational (MNC)", def: "An organisation with production in multiple countries", tr: "nadnárodní korporace", unit: "Primát" },
  { term: "Onboarding", def: "The process of integrating a new employee into a company", tr: "zapracování", unit: "Primát" },
  { term: "Performance appraisal", def: "Evaluation of an employee's work", tr: "hodnocení výkonu", unit: "Primát" },
  { term: "Covering letter", def: "A letter sent with a CV providing extra information", tr: "průvodní / motivační dopis", unit: "Primát" },
  { term: "Whistleblowing", def: "Reporting unethical or illegal behaviour within an organisation", tr: "oznámení neférového jednání", unit: "Primát" },
  { term: "Soar / Rocket / Surge", def: "Rise sharply and suddenly", tr: "prudce vystřelit / vzrůst", unit: "Primát" },
  { term: "Increase / Rise / Grow", def: "Go up (general, gradual)", tr: "zvýšit / stoupat / růst", unit: "Primát" },
  { term: "Jump", def: "A sudden increase", tr: "vyskočit", unit: "Primát" },
  { term: "Plummet / Slump", def: "Fall sharply and suddenly", tr: "zřítit se / propadnout", unit: "Primát" },
  { term: "Decline / Decrease / Fall", def: "Go down (general, gradual)", tr: "klesat / snižovat", unit: "Primát" },
  { term: "Slide / Sink", def: "Slip downward gradually or significantly", tr: "sklouznout / klesat", unit: "Primát" },
  { term: "Level off", def: "Stabilise after rising or falling", tr: "ustálit se", unit: "Primát" },
  { term: "Remain steady/constant", def: "Stay the same, no change", tr: "zůstat beze změny", unit: "Primát" },
  { term: "Fluctuate", def: "Go up and down repeatedly", tr: "kolísat", unit: "Primát" },
  { term: "Reach a peak", def: "Hit the highest point", tr: "dosáhnout vrcholu", unit: "Primát" },
  { term: "Hit a trough / bottom", def: "Reach the lowest point", tr: "klesnout na dno", unit: "Primát" },
  { term: "Bounce back / Recover", def: "Go back up after a fall", tr: "odrazit se zpět", unit: "Primát" },
  { term: "Go down the drain", def: "Something is wasted or lost", tr: "přijít vniveč", unit: "Primát" },
  { term: "Cut to the chase", def: "Get to the important point without wasting time", tr: "přejít k věci", unit: "Primát" },
  { term: "Ahead of the pack", def: "More successful than the competition", tr: "před konkurencí", unit: "Primát" },
  { term: "Easy come, easy go", def: "Something gained easily is also lost easily", tr: "jak přišlo, tak odešlo", unit: "Primát" },
  { term: "Get down to business", def: "Stop small talk, start serious discussion", tr: "pustit se do práce", unit: "Primát" },
  { term: "Big picture", def: "The overall situation, everything involved", tr: "celkový obraz", unit: "Primát" },
  { term: "On the same page", def: "In agreement, understanding each other", tr: "být zajedno", unit: "Primát" },
  { term: "Go out on a limb", def: "Take a risk, do something uncertain", tr: "riskovat", unit: "Primát" },
  { term: "By the book", def: "Exactly according to rules or law", tr: "podle pravidel", unit: "Primát" },
  { term: "Throw in the towel", def: "Give up", tr: "vzdát to", unit: "Primát" },
  { term: "Jump the gun", def: "Act too early, before the right time", tr: "předběhnout události", unit: "Primát" },
  { term: "Get sth off the ground", def: "Start a project or business", tr: "rozběhnout, nastartovat", unit: "Primát" },
  { term: "Back to the drawing board", def: "Start from the beginning again", tr: "začít znovu od začátku", unit: "Primát" },
  { term: "Go the extra mile", def: "Do more than expected", tr: "udělat něco navíc", unit: "Primát" },
  { term: "In a nutshell", def: "In very few words, briefly", tr: "stručně řečeno", unit: "Primát" },
  { term: "For the long haul", def: "Committed for a long time", tr: "na dlouho, dlouhodobě", unit: "Primát" },
  { term: "Cut-throat", def: "Very intense, merciless competition", tr: "nelitostný, nemilosrdný", unit: "Primát" },
  { term: "On the back burner", def: "Low priority, set aside for now", tr: "dát na stranu, odložit", unit: "Primát" },
  { term: "Corner the market", def: "Dominate a particular market", tr: "ovládnout trh", unit: "Primát" },
  { term: "Back to square one", def: "Start over because the previous attempt failed", tr: "zpátky na začátek", unit: "Primát" },
  { term: "rely ON", def: "to depend on something", tr: "spoléhat na", unit: "Primát" },
  { term: "result IN", def: "to lead to / cause", tr: "vést k", unit: "Primát" },
  { term: "focus ON", def: "to concentrate on", tr: "soustředit se na", unit: "Primát" },
  { term: "invest IN", def: "to put money into", tr: "investovat do", unit: "Primát" },
  { term: "comply WITH", def: "to obey rules", tr: "dodržovat", unit: "Primát" },
  { term: "contribute TO", def: "to give to / help with", tr: "přispět k", unit: "Primát" },
  { term: "benefit FROM", def: "to gain advantage from", tr: "těžit z", unit: "Primát" },
  { term: "deal WITH", def: "to handle something", tr: "zabývat se", unit: "Primát" },
  { term: "apply FOR", def: "to request formally (a job)", tr: "žádat o", unit: "Primát" },
  { term: "consist OF", def: "to be made up of", tr: "skládat se z", unit: "Primát" },
  { term: "responsible FOR", def: "in charge of", tr: "zodpovědný za", unit: "Primát" },
  { term: "sticking TO", def: "to follow rules/plan", tr: "držet se", unit: "Primát" },
  { term: "due TO", def: "because of", tr: "kvůli", unit: "Primát" },
];
